using System.Collections.Generic;
using System.IO;
using System.Xml.Serialization;

using UnityEngine;

namespace StoryEngine.Trace {
    /// <summary>
    /// The containing class representing a complete episode story trace.
    /// </summary>
    public class Episode {
        /// <summary>
        /// The unique identifying string for this episode.
        /// </summary>
        public string ID { get; private set; }
        /// <summary>
        /// The InitialState for this episode.
        /// </summary>
        public InitialState InitialState { get; private set; }
        /// <summary>
        /// The collection of StoryEvents contained within this episode.
        /// </summary>
        public List<StoryEvent> Events { get; private set; }

        /// <summary>
        /// Private constructor for the purposes of serialization.
        /// </summary>
        private Episode() {
            this.ID = "unassigned";
        }

        /// <summary>
        /// Deserializes an Episode from an XML string generated by the story generator.
        /// </summary>
        /// <param name="xml">The XML content.</param>
        /// <returns>The Episode from the string data.</returns>
        public static Episode Deserialize(string xml) {
            XmlSerializer serializer = new XmlSerializer(typeof(Episode));

            StringReader reader = new StringReader(xml);
            Episode ep = (Episode)serializer.Deserialize(reader);

            //Convert propositions and storyevents.
            foreach (Proposition prop in ep.InitialState.HealthStatuses) prop.MapVariables();
            foreach (Proposition prop in ep.InitialState.Locations) prop.MapVariables();
            foreach (Proposition prop in ep.InitialState.Possessions) prop.MapVariables();
            foreach (StoryEvent ev in ep.Events) ev.MapVariables();

            Debug.Log("Loaded " + ep.Events.Count + " events into Episode.");

            #region Episode deserilization test...
            //foreach (StoryEvent ev in this.Events) {
            //    string str = ev.Name + ": ";
            //    foreach (Variable v in ev.Variables) {
            //        str += v.Name + " = " + v.Value + ", ";
            //    }
            //    Debug.Log(str);
            //}
            //foreach (Proposition prop in ep.InitialState.Locations) {

            //}
            #endregion

            return ep;
        }
    }
}